ds_course = [['Machine Learning Crash Course by Google [Free]', 'https://developers.google.com/machine-learning/crash-course'],
             ['Machine Learning A-Z by Udemy','https://www.udemy.com/course/machinelearning/'],
             ['Machine Learning by Andrew NG','https://www.coursera.org/learn/machine-learning'],
             ['Data Scientist Master Program of Simplilearn (IBM)','https://www.simplilearn.com/big-data-and-analytics/senior-data-scientist-masters-program-training'],
             ['Data Science Foundations: Fundamentals by LinkedIn','https://www.linkedin.com/learning/data-science-foundations-fundamentals-5'],
             ['Data Scientist with Python','https://www.datacamp.com/tracks/data-scientist-with-python'],
             ['Programming for Data Science with Python','https://www.udacity.com/course/programming-for-data-science-nanodegree--nd104'],
             ['Programming for Data Science with R','https://www.udacity.com/course/programming-for-data-science-nanodegree-with-R--nd118'],
             ['Introduction to Data Science','https://www.udacity.com/course/introduction-to-data-science--cd0017'],
             ['Intro to Machine Learning with TensorFlow','https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230']]

web_course = [['Django Crash course [Free]','https://youtu.be/e1IyzVyrLSU'],
              ['Python and Django Full Stack Web Developer Bootcamp','https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp'],
              ['React Crash Course [Free]','https://youtu.be/Dorf8i6lCuk'],
              ['ReactJS Project Development Training','https://www.dotnettricks.com/training/masters-program/reactjs-certification-training'],
              ['Full Stack Web Developer - MEAN Stack','https://www.simplilearn.com/full-stack-web-developer-mean-stack-certification-training'],
              ['Node.js and Express.js [Free]','https://youtu.be/Oe421EPjeBE'],
              ['Flask: Develop Web Applications in Python','https://www.educative.io/courses/flask-develop-web-applications-in-python'],
              ['Full Stack Web Developer by Udacity','https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044'],
              ['Front End Web Developer by Udacity','https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
              ['Become a React Developer by Udacity','https://www.udacity.com/course/react-nanodegree--nd019']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]

uiux_course = [['Google UX Design Professional Certificate','https://www.coursera.org/professional-certificates/google-ux-design'],
               ['UI / UX Design Specialization','https://www.coursera.org/specializations/ui-ux-design'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['UX & Web Design Master Course: Strategy, Design, Development','https://www.udemy.com/course/ux-web-design-master-course-strategy-design-development/'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['DESIGN RULES: Principles + Practices for Great UI Design','https://www.udemy.com/course/design-rules/'],
               ['Become a UX Designer by Udacity','https://www.udacity.com/course/ux-designer-nanodegree--nd578'],
               ['Adobe XD Tutorial: User Experience Design Course [Free]','https://youtu.be/68w2VwalD5w'],
               ['Adobe XD for Beginners [Free]','https://youtu.be/WEljsc2jorI'],
               ['Adobe XD in Simple Way','https://learnux.io/course/adobe-xd']]

resume_videos = [ 'https://youtu.be/Tt08KmFfIYQ','https://youtu.be/y8YH0Qbu5h4',
                  'https://youtu.be/u75hUSShvnc','https://youtu.be/BYUy1yvjHxE',
                  'https://youtu.be/KFaugkGVeNQ','https://youtu.be/3agP4x8LYFM',
                  'https://youtu.be/GyjzOKdaioU','https://youtu.be/17YZBH_qtmg',
                  'https://youtu.be/C7pNLIq3kOI','https://youtu.be/xpaz7nrNmXA',
                  'https://youtu.be/aKjsy-b00QM','https://youtu.be/ciIkiWwZnlc']

interview_videos = ['https://youtu.be/HG68Ymazo18','https://youtu.be/BOvAAoxM4vg',
                    'https://youtu.be/KukmClH1KoA','https://youtu.be/7_aAicmPB3A',
                    'https://youtu.be/1mHjMNZZvFo','https://youtu.be/WfdtKbAJOmE',
                    'https://youtu.be/IBjM-F56qS0','https://youtu.be/IBjM-F56qS0',
                    'https://youtu.be/4tYoVx0QoN0','https://youtu.be/Ge0Udbws1kc',
                    'https://youtu.be/thkuu_FWFD8','https://youtu.be/e0E6-dRPcJA',
                    'https://youtu.be/htT1bhFSNxo','https://youtu.be/TZ3C_syg9Ow']

swengg_course = [['Introduction to Software Engineering', 'https://www.coursera.org/learn/introduction-to-software-engineering'],
                 ['DevOPS and Software Engineering', 'https://www.coursera.org/professional-certificates/devops-and-software-engineering'],
                 ['Applied Software Engineering and Fundamentals', 'https://www.coursera.org/specializations/software-engineering-fundamentals'],
                 ['Software Design and Architecture', 'https://www.coursera.org/specializations/software-design-architecture'],
                 ['Software Engineering 101: plan and execute better softwares', 'https://www.udemy.com/course/software-engineering-101'],
                 ['Master Software Engineering in C#', 'https://www.udemy.com/course/software-engineering-fundamentals-from-scratch-in-c-sharp'],
                 ['Software Development Fellowship Program', 'https://www.crio.do/software-development-fellowship-program'],
                 ['DevOPS Engineering on AWS', 'https://www.simplilearn.com/aws-devops-certification'],
                 ['Software Development Fundamentals', 'https://www.futurelearn.com/experttracks/software-development-fundamentals'],
                 ['Software Development with Python and Java', 'https://www.futurelearn.com/experttracks/software-development-with-python-and-java']]

blockchain_course = [['Introduction to Blockchain Technologies', 'https://www.coursera.org/learn/introduction-blockchain-technologies'],
                     ['Blockchain Revolution in Finiancial Services', 'https://www.coursera.org/specializations/blockchain-financial-services'],
                     ['Supply Chain Finiance and Blockchain Technology', 'https://www.coursera.org/specializations/supply-chain-finance-and-blockchain-technology'],
                     ['Cryptography and Blockchain', 'https://www.coursera.org/learn/wharton-cryptocurrency-blockchain-introduction-digital-currency'],
                     ['Blockchain A-Z: Build a Blockchain, a Crypto + ChatGPT Prize', 'https://www.udemy.com/course/build-your-blockchain-az'],
                     ['Ethereum Blockchain Developer Bootcamp With Solidity (2024)', 'https://www.udemy.com/course/blockchain-developer'],
                     ['Blockchain and Bitcoin Fundamentals', 'https://www.udemy.com/course/blockchain-and-bitcoin-fundamentals'],
                     ['14 Day Blockchain Developer', 'https://www.udemy.com/course/14-day-blockchain-developer'],
                     ['Certified Blockchain and Supplychain Professional', 'https://www.blockchain-council.org/certifications/certified-blockchain-supply-chain-expert'],
                     ['Blockchain Full Course', 'https://youtu.be/9aXHQ98TMRY']]

aiml_course = [['Applied AI Professional Certificate', 'https://www.coursera.org/professional-certificates/applied-artifical-intelligence-ibm-watson-ai'],
               ['Digital Transformation Using AI/ML with Google Cloud Specialization', 'https://www.coursera.org/specializations/digital-transformation-using-ai-ml-with-google-cloud'],
               ['AI Foundations for Everyone', 'https://www.coursera.org/specializations/ai-foundations-for-everyone'],
               ['AI for Business', 'https://www.coursera.org/specializations/ai-for-business-wharton'],
               ['Mathematical Foundations of Machine Learning', 'https://www.udemy.com/course/machine-learning-data-science-foundations-masterclass'],
               ['Tensorflow Deveeloper Certificate Bootcamp', 'https://www.udemy.com/course/tensorflow-developer-certificate-machine-learning-zero-to-mastery'],
               ['AWS Certified Machine Learning Specialty 2024 - Hands On!', 'https://www.udemy.com/course/aws-machine-learning'],
               ['Machine Learning: Natural Language Processing in Python (V2)', 'https://www.udemy.com/course/natural-language-processing-in-python'],
               ['Tensorflow 2.0: Deep Learning and Artificial Intelligence', 'https://www.udemy.com/course/deep-learning-tensorflow-2'],
               ['Machine Learning Crash Course with TensorFlow APIs', 'https://developers.google.com/machine-learning/crash-course']]
cybersec_course = [['Google Cybersecurity Professional Certificate', 'https://www.coursera.org/google-certificates/cybersecurity-certificate'],
                   ['The Complete Cyber Security Course : Hackers Exposed!', 'https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1'],
                   ['IBM Cybersecurity Analyst Professional Certificate', 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst'],
                   ['Microsoft Cybersecurity Analyst Professional Certificate', 'https://www.coursera.org/professional-certificates/microsoft-cybersecurity-analyst'],
                   ['IT Fundamentals for Cybersecurity Specialization', 'https://www.coursera.org/specializations/it-fundamentals-cybersecurity'],
                   ['Python for Cybersecurity', 'https://www.coursera.org/specializations/pythonforcybersecurity'],
                   ['Cyber Security: From Beginner to Expert (2024)', 'https://www.udemy.com/course/cybersecurity-from-beginner-to-expert'],
                   ['Learn Ethical Hacking from Scratch', 'https://www.udemy.com/course/learn-ethical-hacking-from-scratch'],
                   ['Hack Your Future: Cyber Security Projects for Your Dream Job', 'https://www.udemy.com/course/hack-your-future-cyber-security-projects-for-your-dream-job'],
                   ['Cyber Security Expert', 'https://www.simplilearn.com/cyber-security-expert-master-program-training-course']]

dataengg_course = [['Data Engineering Essentials using SQL, Python, and PySpark', 'https://www.udemy.com/course/data-engineering-essentials-sql-python-and-spark'],
                   ['Databricks Certified Data Engineer Associate - Preparation', 'https://www.udemy.com/course/databricks-certified-data-engineer-associate'],
                   ['Data Engineering using Databricks on AWS and Azure', 'https://www.udemy.com/course/data-engineering-using-databricks-on-aws-and-azure'], 
                   ['Master Data Engineering using GCP Data Analytics', 'https://www.udemy.com/course/master-data-engineering-using-gcp-data-analytics'],
                   ['Azure Data Factory for Beginners - Build Data Ingestion', 'https://www.udemy.com/course/beginning-azure-data-factory'],
                   ['IBM Data Engineering', 'https://www.coursera.org/professional-certificates/ibm-data-engineer'],
                   ['Data Engineering Foundations', 'https://www.coursera.org/specializations/data-engineering-foundations'],
                   ['Python Project for Data Engineering', 'https://www.coursera.org/learn/python-project-for-data-engineering'],
                   ['Cloud Data Engineering', 'https://www.coursera.org/learn/cloud-data-engineering-duke'],
                   ['Data Engineering and Analytics Course', 'https://cloud.google.com/learn/training/data-engineering-and-analytics']]